### ISSUE TITLE
Could you update this, please?

### ISSUE THREAD

**Issue by mickeyl** [oesmith/gatt-xml#1]
Thanks a lot for uploading this!

I wonder whether the files are still current as the per the most recent spec?

**Comment by stefra1** [comment]
Thanks for creating the Bluetooth characteristics.
But I think you have a bug in the indoor_bike_data.xml
Average Speed (Kilometer per hour with a resolution of 0.01) is not included in the Spec:
https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.indoor_bike_data.xml

Stefan

**Comment by stefra1** [comment]
Update, maybe it’s not your fault, “Average Speed” is defined in the FTMS_v1.0 Spec. But not on the definition on the Homepage.

**Comment by mickeyl** [comment]
Is there a way to bulk download the latest spec from bluetooth.com?

**Comment by stefra1** [comment]
https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=423417

**Comment by sur5r** [comment]
@mickeyl See https://github.com/sur5r/gatt-xml
I guess you need to be a BT SIG member to get these links in a straight-forward manner. I added all URLs in `.urllist` to make it a little more reproducible.

**Comment by mickeyl** [comment]
Thanks a lot @sur5r, this is very helpful!
